### ISSUE TITLE
Make bean-check executable configurable

### ISSUE THREAD

**Issue by mariosangiorgio** [mariosangiorgio/beancount-language-server#1]
I knew the hardcoded value was lame, but I just wanted to put a minimum viable product out of the door and leave all the tidying up for later.

@jmgilman is (as far as I know) the first user of the language server and he has `bean-check` in a different location than I do so it's better to make this configurable as soon as possible. It shouldn't be difficult.

**Comment by jmgilman** [comment]
As far as I can tell, VS Code is fairly unaware of the actual language server, other than that it knows where to send the queries to because the client extension tells it. This seems to suggest that VS Code would be unable to communicate configuration settings to the language server. 

What's the plan for getting the configuration value to the language server?

**Comment by mariosangiorgio** [comment]
It's supported by the language server protocol. [This example](https://code.visualstudio.com/docs/extensions/example-language-server) shows how to configure an extension in Visual Studio Code and have the settings synchronised to the language server.

Unfortunately I haven't had a chance to implement it this evening. I'll do it as soon as I have a spare hour

**Comment by mariosangiorgio** [comment]
This has been done in [my development branch of the extension](https://github.com/mariosangiorgio/vscode-beancount/tree/completion). It now reads the executable from configuration and provides a message if it cannot find the file specified.
